name: Continuous Delivery
on:
  push:
    branches:
      - main # ou qualquer outra branch

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado.zip
          path: |
            '**.py'
            README.md
          retention-days: 5

  warning:
      - name: Create a file
        run: echo "O ZIP VAI APENAS DURAR 5 DIAS!" > my_file.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aviso
          path: my_file.txt
          retention-days: 5